networks:
  pluspoint_network:
    driver: bridge
    name: pluspoint

services:

  fastapi_pluspoint:
    build: ./backend
    container_name: fastapi_pluspoint
    # depends_on:
    #   - kafka_pluspoint_1
    #   - kafka_pluspoint_2
    #   - celery_pluspoint
    #   - mongodb_pluspoint
    env_file:
      - ./backend/.env
    restart: always
    volumes:
      - ./backend/app:/app/app 
      - ./backend/images/kyc:/app/images/kyc
      - ./backend/images/profile:/app/images/profile
    ports:
      - "5000:5000"
    networks:
      - pluspoint_network

  kafka_pluspoint_1:
    image: confluentinc/cp-kafka:latest
    container_name: kafka_pluspoint_1
    ports:
      - "29092:9092"   # Host:Container
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: "broker,controller"
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka_pluspoint_1:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka_pluspoint_1:9093"
      KAFKA_CLUSTER_ID: "VzJk8iGjR9ePrwxmXKZauw"
      KAFKA_LOG_DIRS: /var/lib/kafka/data
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
    healthcheck:
      test: nc -z kafka_pluspoint_1 9092 || exit 1
      interval: 5s
      retries: 10
      timeout: 3s
    networks:
      - pluspoint_network

  # kafka_pluspoint_2:
  #   image: confluentinc/cp-kafka:latest
  #   container_name: kafka_pluspoint_2
  #   ports:
  #     - "29094:9094"
  #   environment:
  #     KAFKA_NODE_ID: 2
  #     KAFKA_PROCESS_ROLES: "broker"
  #     KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9094
  #     KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka_pluspoint_2:9094
  #     # KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
  #     KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka_pluspoint_1:9093"
  #     KAFKA_CLUSTER_ID: "VzJk8iGjR9ePrwxmXKZauw"
  #     KAFKA_LOG_DIRS: /var/lib/kafka/data
  #     KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
  #     KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
  #     KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
  #     KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
  #     KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT
  #     KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
  #   healthcheck:
  #     test: nc -z kafka_pluspoint_2 9094 || exit 1
  #     interval: 5s
  #     retries: 10
  #     timeout: 3s
  #   networks:
  #     - pluspoint_network

  # kafka_pluspoint_3:
  #   image: confluentinc/cp-kafka:latest
  #   container_name: kafka_pluspoint_3
  #   ports:
  #     - "29096:9096"
  #   environment:
  #     KAFKA_NODE_ID: 3
  #     KAFKA_PROCESS_ROLES: "broker,controller"
  #     KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9096,CONTROLLER://0.0.0.0:9097
  #     KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka_pluspoint_3:9096
  #     KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
  #     KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka_pluspoint_1:9093,2@kafka_pluspoint_2:9095,3@kafka_pluspoint_3:9097"
  #     KAFKA_CLUSTER_ID: "<your-cluster-id>"
  #     KAFKA_LOG_DIRS: /var/lib/kafka/data
  #     KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
  #     KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 3
  #     KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 2
  #     KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
  #   healthcheck:
  #     test: nc -z kafka_pluspoint_3 9096 || exit 1
  #     interval: 5s
  #     retries: 10
  #     timeout: 3s
  #   networks:
  #     - pluspoint_network

  mongodb_pluspoint:
    image: mongo:6
    container_name: mongodb_pluspoint
    restart: always
    env_file:
      - ./backend/.env
    # environment:
    #   MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
    #   MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    #   MONGO_INITDB_DATABASE: ${MONGO_DB_NAME}
    ports:
      - "27018:27017" 
    volumes:
      - mongo_data:/data/db
    networks:
      - pluspoint_network

  redis_pluspoint:
    image: redis:7-alpine
    container_name: redis_pluspoint
    ports:
      - "6379:6379"
    networks:
      - pluspoint_network

  celery_pluspoint:
    build: ./backend
    container_name: celery_pluspoint
    command: celery -A app.celery.worker worker --loglevel=info --concurrency=2
    depends_on:
      - redis_pluspoint
      - mongodb_pluspoint
    env_file:
      - ./backend/.env
    volumes:
      - ./backend/app:/app/app
    networks:
      - pluspoint_network

  flower_pluspoint:
    image: mher/flower:2.0
    container_name: flower_pluspoint
    command: >
      celery
      --broker=redis://redis_pluspoint:6379/0
      flower
      --port=5555
    ports:
      - "5555:5555"
    depends_on:
      - redis_pluspoint
      - celery_pluspoint
    networks:
      - pluspoint_network

  frontend_pluspoint:
    image: nginx:alpine
    container_name: frontend_pluspoint
    restart: always
    ports:
      - "3000:80"       # Map localhost:3000 → Nginx
    volumes:
      - ./frontend:/usr/share/nginx/html
    networks:
      - pluspoint_network

  # kafka-ui:
  #   image: provectuslabs/kafka-ui
  #   container_name: kafka-ui
  #   ports:
  #     - "8090:8080"
  #   restart: always
  #   environment:
  #     KAFKA_CLUSTERS_0_NAME: local
  #     KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka_pluspoint_1:9092,kafka_pluspoint_2:9094
  #   networks:
  #     - pluspoint_network

volumes:
  mongo_data:
  data:
