version: "3.8"

services:
  fastapi_pluspoint:
    build: .
    container_name: fastapi_pluspoint
    ports:
      - "5000:5500"
    depends_on:
      - mysql_pluspoint
    env_file:
      - .env
    restart: always

  mysql_pluspoint:
    image: mysql:8
    container_name: mysql_pluspoint
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: testdb
    ports:
      - "3306:3308"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
