version: "3.9"

services:
  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: fastapi_db
    ports:
      - "5431:5432"   # external 5431 → internal 5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: .
    container_name: fastapi_app
    restart: always
    depends_on:
      - db
    env_file: 
      - .env
    ports:
      - "8001:8000"   # external 8001 → internal 8000
    volumes:
      - ./app:/code/app
      - ./requirements.txt:/code/requirements.txt

volumes:
  postgres_data:
